
CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role ENUM('donor', 'ngo', 'super_admin') NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
