<?php
// Generated by setup_mariadb_project.sh — edit as needed.
define('DB_HOST', '127.0.0.1');
define('DB_NAME', 'app_30953');
define('DB_USER', 'app_30953');
define('DB_PASS', 'e45f2778-db1f-450c-99c6-29efb4601472');

function db() {
  static $pdo;
  if (!$pdo) {
    $pdo = new PDO('mysql:host='.DB_HOST.';dbname='.DB_NAME.';charset=utf8mb4', DB_USER, DB_PASS, [
      PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
      PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
    ]);
    run_migrations($pdo);
  }
  return $pdo;
}

function run_migrations($pdo) {
    $pdo->exec("CREATE TABLE IF NOT EXISTS migrations (migration VARCHAR(255) PRIMARY KEY)");
    $applied_migrations = $pdo->query("SELECT migration FROM migrations")->fetchAll(PDO::FETCH_COLUMN);

    $migration_files = glob(__DIR__ . '/migrations/*.sql');
    foreach ($migration_files as $file) {
        $migration_name = basename($file);
        if (!in_array($migration_name, $applied_migrations)) {
            $sql = file_get_contents($file);
            $pdo->exec($sql);
            $pdo->prepare("INSERT INTO migrations (migration) VALUES (?)")->execute([$migration_name]);
        }
    }
}
